### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by caizixian** [caizixian/tcpstat#1]
- [x] Basic function(Load iptables input & output parsed data)
- [x] Config file & command line argument
- [x] Database migration
- [x] DONOT simply flush chains.
- [x] Database backend
- [ ] Multi backend
- [x] Cron
- [x] Distribute(PyPI)
- [ ] Add new entry at beginning of the day
- [ ] Webhook and introducing requests
- [ ] Unit Test
- [ ] Document
- [x] Lock mechanism to prevent update during migration
- [ ] Config validator
- [ ] Match comment to improve performance
- [ ] Auto update before migrate
- [ ] Remove iptables dependency
